# Generated by Django 5.0.3 on 2024-03-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_carta_dibujo_figura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dibujo',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='figura',
            name='material',
            field=models.CharField(max_length=100),
        ),
    ]
