# Generated by Django 5.0.3 on 2024-03-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_rename_tipo_dibujo_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={'ordering': ['nombre']},
        ),
    ]
