# Generated by Django 5.0.3 on 2024-03-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_camiseta_precio_carta_precio_dibujo_precio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camiseta',
            old_name='precio',
            new_name='precio_USD',
        ),
        migrations.RenameField(
            model_name='carta',
            old_name='precio',
            new_name='precio_USD',
        ),
        migrations.RenameField(
            model_name='dibujo',
            old_name='precio',
            new_name='precio_USD',
        ),
        migrations.RenameField(
            model_name='figura',
            old_name='precio',
            new_name='precio_USD',
        ),
    ]
